[package]
name = "bank_core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1", features = ["rt-multi-thread", "macros"] }
axum = "0.7"

reqwest = { version = "0.12", features = ["blocking"] }